### ISSUE TITLE
Derive amount of rows and columns directly from grid

### ISSUE THREAD

**Issue by incredibleLeitman** [geordzNZ/SlotMachine#1]
Instead of having hardcoded borders
https://github.com/geordzNZ/SlotMachine/blob/8487dc67b70e8be9092648285005d4a41c5dc147/SlotMachine/Program.cs#L28-L30

you could derive the amount of rows and cols directly from the array using GetLength:
https://learn.microsoft.com/en-us/dotnet/api/system.array.getlength?view=net-7.0

This way your code is more generic and easier to maintain if you later decide for example to show more lines

Also instead of i, j, k,... you should name your variables more specific

**Comment by geordzNZ** [comment]
Ok I see what you mean about the GetLength ... 
But I went a different route and defined the size of the grid in Const's ...hope that is OK.

**Comment by incredibleLeitman** [comment]
I think this is ok for this project 👍 

But keep in mind that this restricts your program in a way that if you want to later release a new, modified version of your program with different grid sizes you need to change those constants and re-compile your code.

Having generic methods that always work with the present data are much more stable to such kind of modifications.
