### ISSUE TITLE
this variables could be shorter

### ISSUE THREAD

**Issue by incredibleLeitman** [geordzNZ/SlotMachine#11]
https://github.com/geordzNZ/SlotMachine/blob/1607387d900ac82486613d5a05aa626621b9e703/SlotMachine/Program.cs#L29-L31
in this case it does not matter if the loop is for creation and it is obvious that is a counter (because it is declared in the loop header) so just "row" and "col" would suffice

**Comment by geordzNZ** [comment]
Over compensating there a bit I guess 🤣
