### ISSUE TITLE
move bet deduction directly after input validation

### ISSUE THREAD

**Issue by incredibleLeitman** [geordzNZ/SlotMachine#12]
https://github.com/geordzNZ/SlotMachine/blob/1607387d900ac82486613d5a05aa626621b9e703/SlotMachine/Program.cs#L175

to make your program flow more consistent and readable:
User selects lines -> reduce bet -> check lines hit -> grant win

**Comment by geordzNZ** [comment]
SHESH!!!!! Honestly, I did have that at one point, but then I changed it so that the calc's were together as they felt a bit in the middle of nowhere by them selves.
