### ISSUE TITLE
Consider granting more on a win than just the bet

### ISSUE THREAD

**Issue by incredibleLeitman** [geordzNZ/SlotMachine#14]
Currently each hit line just basically "refunds" the bet so there is no intention of winning in your game... in the best case the user can just get the same amount of geoz back, but usually its less.

Make sure you put the possible winning also in the printed introduction

**Comment by geordzNZ** [comment]
I did have that intention early on in the code, even had a variable for it (lineStake) ... but then just never implemented it ... maybe I'm too greedy ... the House always wins!!
Will implement though ... with a little bonus too...

**Comment by incredibleLeitman** [comment]
Nice, I pretty much like this idea :D

But now that you did an additional bonus calculation, you should definitely show the user when he manages to win the "jackpot" (or something like that) and that the bet gets refunded :D
