### ISSUE TITLE
reorder continue condition

### ISSUE THREAD

**Issue by incredibleLeitman** [geordzNZ/SlotMachine#15]
https://github.com/geordzNZ/SlotMachine/blob/1607387d900ac82486613d5a05aa626621b9e703/SlotMachine/Program.cs#L76-L94

Currently you check if there was non-empty input and extract the valid choices.
But if the user would enter invalid values like "123..." the Length == 0 check would not trigger,
but there were no valid option.

If you first execute the extraction loop (which just does nothing if the given string is empty) and *later* check if the valid options are > 0 this would also cover the case where the user enters text, but none of the valid options were given

**Comment by incredibleLeitman** [comment]
also think about if you really need to declare
```
string lineSelectionInput = "";
```
outside of the loop, because you never use it afterwards

**Comment by geordzNZ** [comment]
yeah fair point ... the lineSelectionInput declaration was needed at some point ... way back when ... I think that was before I got the line validations working.
updated
