### ISSUE TITLE
Don't initialize Random within a function or a loop

### ISSUE THREAD

**Issue by incredibleLeitman** [geordzNZ/SlotMachine#16]
prefer to create your random generator on top of your main and provide it as param to functions or even assign it as static readonly object so you can use it in other modules
https://github.com/geordzNZ/SlotMachine/blob/53634845978de4de4d43bf2f32c19253ab78631a/SlotMachine/Program.cs#L30

**Comment by geordzNZ** [comment]
thought I'd done this one before ... but didnt move it up enough.
