### ISSUE TITLE
Is this condition correct?

### ISSUE THREAD

**Issue by incredibleLeitman** [geordzNZ/SlotMachine#18]
https://github.com/geordzNZ/SlotMachine/blob/53634845978de4de4d43bf2f32c19253ab78631a/SlotMachine/Program.cs#L135-L138

Because this means if the user is playing only one line, the top row for example, matching this line, 
he gets the usual winning plus the bet refund?
I just assumed that this bonus is only granted for more than one line, but of  course you can implement it as you want :D

In any way I would like to give some notice to the user if the bet is refunded in form of some additional output

**Comment by geordzNZ** [comment]
The condition is all cool ... I wanted the bonus to kick in if they got 100%, even if it was just 1 line they bet on.
