### ISSUE TITLE
Create random outside loops

### ISSUE THREAD

**Issue by incredibleLeitman** [geordzNZ/SlotMachine#2]
https://github.com/geordzNZ/SlotMachine/blob/8487dc67b70e8be9092648285005d4a41c5dc147/SlotMachine/Program.cs#L32
Although in this little project this really does not have much impact, 
but creating a new Random object within a loop can be bad for performance and even lead to errors creating the same numbers over and over.

It is preferable to create such Objects outside of loops, 
if you plan to use it in multiple functions even outside of functions.
For example, you could create a random static field for your Random Generator that gets only instantiated once for your entire program and can be used in multiple functions

**Comment by geordzNZ** [comment]
have moved it, will probably need to move it again, based on getting a fuller game loop, will deal with that when I get to that issue
