### ISSUE TITLE
No need to declace two messages and override the value just for print

### ISSUE THREAD

**Issue by incredibleLeitman** [geordzNZ/SlotMachine#22]
https://github.com/geordzNZ/SlotMachine/blob/1ec603a58563bca81ec8f146f687517a5af74aad/SlotMachine/UIMethods.cs#L191-L206

If you don't have a specific default case or using a switch, you can just print the corresponding message direction in the conditions

**Comment by geordzNZ** [comment]
OK sure, going to over the top there I guess :-)
