### ISSUE TITLE
You don't need to pass a const variable

### ISSUE THREAD

**Issue by incredibleLeitman** [geordzNZ/SlotMachine#23]
https://github.com/geordzNZ/SlotMachine/blob/1ec603a58563bca81ec8f146f687517a5af74aad/SlotMachine/LogicMethods.cs#L103
If you make it public accessible.

https://github.com/geordzNZ/SlotMachine/blob/1ec603a58563bca81ec8f146f687517a5af74aad/SlotMachine/Program.cs#L12

Usually you try to keep the list of parameters small and only to allow the function to handle specific behavior depending on those.
In this case, "payout" is always set to WIN_AMOUNT which means you can just access this constant within the function like
Program.WIN_AMOUNT (if it is declared public)

The same applies for the GenerateSlotGrid function using SLOTS_MAX_VALUE

**Comment by geordzNZ** [comment]
I'd tried making them public initially, but it didnt work and was part of the thing that I found to be hard with this task.
I see now that I had forgotten to prefix it with Program.  Sorted now though.
