### ISSUE TITLE
conditions could be merged

### ISSUE THREAD

**Issue by incredibleLeitman** [geordzNZ/SlotMachine#3]
https://github.com/geordzNZ/SlotMachine/blob/8487dc67b70e8be9092648285005d4a41c5dc147/SlotMachine/Program.cs#L56-L73

The first condition just sets a value that is used by a second one to handle the result.
In your current implementation you could just merge those two into one,
although, with the next step of this project being to split up your code into ui and logic functions,
it is wise to instead keep the setting of the flag. But in this way you should also rearrange your code a bit:
The condition can be seen as a "does the player hit a line" block that just sets the "win" flag,
and the block after that is handling the result such as printing the info to the user and granting the win.

**Comment by geordzNZ** [comment]
I can see what you are saying, that the 2 blocks could have been merged, agreed ... not sure why I didnt in the first place, except, perhaps I was leaving that first block for the 'checking' and to set the win flag.

I think you are saying that, based on what is coming in the next section, it is OK as it is for now?

**Comment by incredibleLeitman** [comment]
I think you can keep the structure of two block because that will help you later for separating into methods,
but still should modify it according to my feedback:
the first block is just for determination if the player has hit a line and set a flag,
and the second block should handle the result such as printing win/no win and grant the credits.

The deduction of a bet should happen before due to some reasons:
Each "play" cost a certain amount of credits and should be deducted if the user wants to play another round,
the granting of win credits depends on the hit lines, which is a different task.
In the current project this is not as obvious, but imagine this project was build in a server-client application: The user could try to play another round and as soon as he sees that there is no win just close the program (or an could error happen) and he does not have to pay the bet

**Comment by geordzNZ** [comment]
Think this can be closed off now as have separated the 2 main conditions and fixed up the calc's (also related to #7)
