### ISSUE TITLE
Loop to let users play more often and different variations

### ISSUE THREAD

**Issue by incredibleLeitman** [geordzNZ/SlotMachine#4]
Currently there is only one try that runs the slotmachine and then the program stops.

I think you should for one thing embed your game-logic within a loop that allows players to play again (and then you probly need some variable to keep track of their credits)
and also maybe a option list on which lines to play: at the moment you only check the middle line,
but what if the user wants to also play vertical lines, diagonals or even all lines?

**Comment by geordzNZ** [comment]
I'd left it only checking the middle line and doing the basic money tracking at the moment as that is what is mentioned in the check list. 
The description of the task mentions checking other lines combo's ... but the tasks then don't go into mentioning them.

Gues you are mentioning them now then... will get on it.

**Comment by incredibleLeitman** [comment]
The task list of the Trello card is just to provide a path for the exercise to help our clients start into the right direction,
but the exercise clearly states "They can play center line, all three horizontal lines, all vertical lines and diagonals." so yes please implement that too :D

**Comment by geordzNZ** [comment]
Ok sure. I saw it the other way, but will keep it in mind going forwards....
working on the rest of stuff as I go now too
