### ISSUE TITLE
Clearer user instructions

### ISSUE THREAD

**Issue by henrikmdev** [geordzNZ/SlotMachine#6]
https://github.com/geordzNZ/SlotMachine/blob/d8870a94f90a6db4954621b505c2ff8388e441b7/SlotMachine/Program.cs#L71

Based on your code, it looks like the user can input the line selections without anything in between them like "tmbl".

But without looking at your code, it isn't clear how the user should make his or her selections. Maybe let the user know what kind of format he or she should follow to make the input.

**Comment by geordzNZ** [comment]
there is this line in the heading section ...
`                Console.WriteLine($"\t\t...ie to play the top / left / down / right lines  ... enter tldr");`

but also I see line 71 with the slashes, is more confusing that needed. (I'd hoped it would be read as just the options to choose.)
