### ISSUE TITLE
Recommendation: no do while loops

### ISSUE THREAD

**Issue by henrikmdev** [geordzNZ/SlotMachine#9]
https://github.com/geordzNZ/SlotMachine/blob/d8870a94f90a6db4954621b505c2ff8388e441b7/SlotMachine/Program.cs#L68
https://github.com/geordzNZ/SlotMachine/blob/d8870a94f90a6db4954621b505c2ff8388e441b7/SlotMachine/Program.cs#L212

This is just my preference, but I recommend you use a normal while loop instead of a do while. I think it's easier to understand what's going on (for someone taking a glance at your code and your future self) if you know the condition of the loop right away instead of scrolling all the way down to see what the condition of the loop is. Also, most people use while loops. I rarely see do while loops.

**Comment by geordzNZ** [comment]
My thinking for using the do while ... is that I wanted the loop to run at least once (to show at least one of the prompts), so with the while (condition) at the bottom, it will do that.
I see what you are saying about reading the code and the condition being at the top ... will keep it in mind for the future
